config/urls.py
from django.contrib import admin
from django.urls import path, include

from rassilki.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rassilki.urls', namespace='rassilki')),
    path('users/', include('users.urls', namespace='users')),
]

rassilki/urls.py
from django.urls import path

from rassilki.apps import RassilkiConfig
from rassilki.views import HomePageView, ClientCreateView, MailingCreateView, ClientDetailView, ClientUpdateView, \
    ClientDeleteView, contacts, ClientListView, MailingListView, MailingDetailView, MailingUpdateView, \
    MailingDeleteView, index

app_name = RassilkiConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('', index, name='index'),
    path('client_form/', ClientCreateView.as_view(), name='client-create'),
    path('client/', ClientListView.as_view(), name='client-list'),
    path('client/<int:pk>/detail/', ClientDetailView.as_view(), name='client-detail'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client-update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),

    path('contacts/', contacts, name='contacts'),

    path('create_mailing/', MailingCreateView.as_view(), name='mailing-create'),
    path('mailing/', MailingListView.as_view(), name='mailing-list'),
    path('mailing/<int:pk>/detail/', MailingDetailView.as_view(), name='mailing-detail'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing-update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing-delete'),

]

users/urls.py
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [

]

rassilki/models.py
from datetime import datetime, timedelta

from django.core.mail import send_mail
from django.db import models
from django.utils import timezone

NULLABLE = {'null': True, 'blank': True}


# Модель Клиент сервиса
class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='Email')
    full_name = models.CharField(max_length=255, verbose_name='Full name', **NULLABLE)
    comment = models.TextField(blank=True, null=True, verbose_name='Comment')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


# Модель рассылки
class MailingMessage(models.Model):
    FREQUENCY_CHOICES = (
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    )
    FIRST_CHOICES = (
        ('1', 'закончить'),
        ('2', 'сохранить'),
        ('3', 'запустить'),
    )

    subject = models.CharField(max_length=255)
    body = models.TextField(max_length=255)
    send_time = models.TimeField(verbose_name='Send time', )
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES, default='daily')
    status = models.CharField(choices=FIRST_CHOICES, verbose_name='Status',
                              default='3')
    client = models.ManyToManyField(Client, verbose_name='Clients')

    def __str__(self):
        return f"{self.body}"

    # def get_next_time_run(self) -> datetime:
    #     """Return next time run"""
    #     now = timezone.now()
    #     if self.send_time >= now.time():
    #         # Если время отправки больше или равно текущему времени сейчас, отправляем сегодня
    #         next_datetime = now.today()
    #     else:
    #         # Иначе отправляем завтра
    #         next_datetime = now.today() + timedelta(days=1)
    #
    #         # Далее добавляем интервал в зависимости от выбранной периодичности
    #         if self.frequency == 'daily':
    #             pass  # Оставляем без изменений, так как уже учтено в вычислениях выше
    #         elif self.frequency == 'weekly':
    #             next_datetime += timedelta(weeks=1)
    #         elif self.frequency == 'monthly':
    #             next_datetime += timedelta(days=30)  # Простое добавление дней
    #
    #         # Объединяем полученное дату и время отправки, чтобы получить полное время отправки
    #         next_time_run = datetime.combine(next_datetime, self.send_time)
    #

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


# Модель логов
class Log(models.Model):
    STATUS_SUCCESSFUL = 'SUCCESS'
    STATUS_FAILED = 'FAILED'

    STATUS_CHOICES = (
        (STATUS_SUCCESSFUL, 'Success'),
        (STATUS_FAILED, 'Failed'),
    )

    log_created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation Time', **NULLABLE, )
    log_status = models.CharField(max_length=50, choices=STATUS_CHOICES, verbose_name='Status', **NULLABLE)
    log_client = models.ForeignKey(Client, on_delete=models.SET_NULL, verbose_name='Client', **NULLABLE, )
    log_mailing = models.ForeignKey(MailingMessage, on_delete=models.CASCADE, verbose_name='Mailing', **NULLABLE, )
    log_server_response = models.TextField(**NULLABLE, verbose_name='Server response', )

    def __str__(self):
        return f"{self.log_client} - {self.log_status}"

    class Meta:
        verbose_name = 'Log'
        verbose_name_plural = 'Logs'

rassilki/forms.py
from django import forms
from .models import Client, MailingMessage


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'full_name', 'comment']


class MailingMessageForm(forms.ModelForm):
    class Meta:
        model = MailingMessage
        fields = ['subject', 'body', 'send_time', 'frequency', 'status', 'client']

rassilki/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import Http404
from .forms import ClientForm, MailingMessageForm
from .models import Client, MailingMessage


class HomePageView(ListView):
    model = Client
    template_name = 'rassilki/home.html'


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('rassilki:home')

    def get_context_data(self, **kwargs):
        context = super(ClientCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Новый клиент'
        return context

    def get_success_url(self):
        return reverse('rassilki:client-detail', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.client_owner = self.request.user
        self.object.save()
        return redirect(self.get_success_url())


class ClientListView(ListView):
    model = Client
    template_name = 'rassilki/client_list.html'

    def get_context_data(self, **kwargs):
        context = super(ClientListView, self).get_context_data(**kwargs)
        context['title'] = 'Клиенты'
        return context

    def get_queryset(self):
        return super().get_queryset()


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'rassilki/client_form.html'

    def get_context_data(self, **kwargs):
        context = super(ClientUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Edit Clients'
        return context

    def get_success_url(self):
        return reverse('rassilki:client-detail', args=[self.object.pk])


class ClientDetailView(DetailView):
    model = Client
    template_name = 'rassilki/client_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ClientDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Clients Details'
        return context


class ClientDeleteView(DeleteView):
    model = Client
    template_name = 'rassilki/client_confirm_delete.html'
    success_url = reverse_lazy('rassilki:client-list')

    def get_context_data(self, **kwargs):
        context = super(ClientDeleteView, self).get_context_data()
        context['title'] = 'Delete Client'
        return context


def contacts(requests):
    if requests.method == 'POST':
        name = requests.POST.get('name')
        email = requests.POST.get('email')
        subject = requests.POST.get('subject')
        message = requests.POST.get('message')

    context = {
        'title': 'Contact Us',
    }

    return render(requests, 'rassilki/contacts.html', context)


class MailingCreateView(CreateView):
    model = MailingMessage
    form_class = MailingMessageForm
    template_name = 'rassilki/create_mailing.html'

    def get_success_url(self):
        return reverse('rassilki:mailing-detail', args=[self.object.pk])


class MailingListView(ListView):
    model = MailingMessage
    template_name = 'rassilki/mailing_list.html'

    def get_queryset(self):
        return super().get_queryset()


class MailingUpdateView(UpdateView):
    model = MailingMessage
    form_class = MailingMessageForm
    template_name = 'rassilki/create_mailing.html'

    def get_success_url(self):
        return reverse('rassilki:mailing-detail', args=[self.object.pk])


class MailingDetailView(DetailView):
    model = MailingMessage
    template_name = 'rassilki/mailing_detail.html'

    def get_context_data(self, **kwargs):
        context = super(MailingDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Campaign Details'
        return context


class MailingDeleteView(DeleteView):
    model = MailingMessage
    template_name = 'rassilki/mailing_confirm_delete.html'
    success_url = reverse_lazy('rassilki:mailing-list')

    def get_context_data(self, **kwargs):
        context = super(MailingDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Delete Campaign'
        return context


def index(request):
    return render(request, 'rassilki/index.html')

rassilki/templates/rassilki/client_confirm_delete.html
{% extends 'rassilki/home.html' %}
{% load static %}

{% block content %}
    <div class="col-12" align="center">
        <div class="rom ">
            <div class="col-6">
                <div class="card no-hover">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Are you sure you want to delete this Product: {{ object.title|title }}</p>
                            <button type="submit" class="btn btn-danger">Confirm Delete</button>
                            <a href="{% url 'rassilki:mailing-detail' object.pk  %}" class="btn btn-warning">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

rassilki/templates/rassilki/client_detail.html
{% extends 'rassilki/home.html' %}

{% block content %}
<style>
    .email-table {
        width: 100%;
        border-collapse: collapse;
    }

    .email-table th, .email-table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    .email-table th {
        background-color: #f2f2f2;
    }

    .email-table tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .email-table tr:hover {
        background-color: #ddd;
    }

    .subscribers-list {
        list-style-type: none;
        padding: 0;
    }

    .subscribers-list li {
        margin-bottom: 4px;
    }

    .button-container {
        margin-top: 10px;
        text-align: right;
    }

    .button-container a {
        text-decoration: none;
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border-radius: 5px;
        margin-right: 10px;
        display: inline-block;
    }

    .button-container a:hover {
        background-color: #0056b3;
    }
</style>

<table class="email-table">
    <thead>
        <tr>
            <th>Email Subject</th>
            <th>Full Name:</th>

        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.email }}</td>
            <td>{{ object.full_name}}</td>
        </tr>
    </tbody>
</table>
<div class="button-container">
    <a href="{% url 'rassilki:client-delete' object.pk %}">Delete</a>
    <a href="{% url 'rassilki:client-update' object.pk %}">Edit</a>
    <a href="{% url 'rassilki:client-list' %}">Back to Clients</a>
</div>
{% endblock %}

rassilki/templates/rassilki/client_form.html
{%extends 'rassilki/home.html'%}
{% block content %}
<style>
     .form-container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
        box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
    }

    .btn {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 3px;
        font-size: 16px;
    }

    .btn {
        background-color: #007BFF;
        color: #fff;
        border: none;
        cursor: pointer;
    }

    .btn:hover {
        background-color: #0056b3;
    }
</style>
<div class="form-container">
    <h1>Заполните данные клиента:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
</div>
{% endblock %}

rassilki/templates/rassilki/client_list.html
{% extends 'rassilki/home.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <a href="{% url 'rassilki:client-create' %}" class="btn btn-primary create-client-button">Add Client</a>
        </div>
    </div>

    <div class="row mt-4">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-3 custom-card">
                <div class="card-body">
                    <h4 class="card-title">{{ object.email }}</h4>
                    <hr class="divider">
                    <p class="card-text"><strong>First Name:</strong> {{ object.full_name }}</p>
                    <p class="card-text"><strong>Comment:</strong> {{ object.comment }}</p>
                </div>
                <div class="card-footer bg-transparent border-top-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'rassilki:client-detail' object.pk %}" class="btn btn-outline-primary btn-sm">Details</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<style>

    .create-client-button {
        margin-top: 20px;
    }

    .custom-card {
        border: 1px solid #e0e0e0;
        border-radius: 10px;
        transition: transform 0.2s;
    }

    .custom-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .divider {
        margin-top: 10px;
        margin-bottom: 10px;
        border: none;
        height: 1px;
        background-color: #e0e0e0;
    }

    .card-title {
        font-size: 1.5rem;
        color: #333;
    }

    .card-text {
        color: #555;
    }

    .btn-outline-primary {
        color: #007bff;
        border-color: #007bff;
    }
</style>

{% endblock %}

rassilki/templates/rassilki/contacts.html
{% extends 'rassilki/home.html' %}

{% block content %}
<style>
    .card {
        background-color: #f9f9f9;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
    }

    .card-title {
        font-size: 18px;
        font-weight: bold;
    }

    .card-text {
        font-size: 16px;
    }
</style>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-4 no-hover">
            <div class="card-body">
                <h4 class="card-title">Контактная информация</h4>
                <p class="card-text">
                    <strong>Moscow:</strong> +7 000 000 000 00<br>
                    <strong>St. Petersburg:</strong> +7 800 000 000 00
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

rassilki/templates/rassilki/create_mailing.html
{% extends 'rassilki/home.html' %}

{% block content %}
<style>
    .form-container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
        box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
    }

    .btn {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 3px;
        font-size: 16px;
    }

    .btn {
        background-color: #007BFF;
        color: #fff;
        border: none;
        cursor: pointer;
    }

    .btn:hover {
        background-color: #0056b3;
    }
</style>
<div class="form-container">
    <h1>Заполните данные для рассылки</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
</div>
{% endblock %}

rassilki/templates/rassilki/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/product.css' %}" rel="stylesheet">
</head>

<body>

<nav class="site-header sticky-top py-1">
    <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="{% url 'rassilki:index' %}">
            <svg class="d-block mx-auto" fill="none" height="24" stroke="currentColor" stroke-linecap="round"
                 stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24"
                 xmlns="http://www.w3.org/2000/svg">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="14.31" x2="20.05" y1="8" y2="17.94"></line>
                <line x1="9.69" x2="21.17" y1="8" y2="8"></line>
                <line x1="7.38" x2="13.12" y1="12" y2="2.06"></line>
                <line x1="9.69" x2="3.95" y1="16" y2="6.06"></line>
                <line x1="14.31" x2="2.83" y1="16" y2="16"></line>
                <line x1="16.62" x2="10.88" y1="12" y2="21.94"></line>
            </svg>
        </a>

        <a class="py-2 d-none d-md-inline-block" href="{% url 'rassilki:index' %}">Home</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'rassilki:mailing-list' %}">Campaign</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'rassilki:client-list' %}">Clients</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'rassilki:contacts' %}">Contacts</a>
    </div>
</nav>

<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
            <p class="lead text-muted">{{ description }}</p>
            <p>
            </p>
        </div>

        <!-- Campaign content -->
        <div class="album py-5">
            <div class="container">
                <div class="row">
                    <!-- Mailing content -->
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
    <footer>
        <footer class="container py-5">
    <div class="row">
        <div class="col-12 col-md">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="d-block mb-2">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="14.31" y1="8" x2="20.05" y2="17.94"></line>
                <line x1="9.69" y1="8" x2="21.17" y2="8"></line>
                <line x1="7.38" y1="12" x2="13.12" y2="2.06"></line>
                <line x1="9.69" y1="16" x2="3.95" y2="6.06"></line>
                <line x1="14.31" y1="16" x2="2.83" y2="16"></line>
                <line x1="16.62" y1="12" x2="10.88" y2="21.94"></line>
            </svg>
            <small class="d-block mb-3 text-muted">© 2017-2018</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Cool stuff</a></li>
                <li><a class="text-muted" href="#">Random feature</a></li>
                <li><a class="text-muted" href="#">Team feature</a></li>
                <li><a class="text-muted" href="#">Stuff for developers</a></li>
                <li><a class="text-muted" href="#">Another one</a></li>
                <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Resource</a></li>
                <li><a class="text-muted" href="#">Resource name</a></li>
                <li><a class="text-muted" href="#">Another resource</a></li>
                <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Business</a></li>
                <li><a class="text-muted" href="#">Education</a></li>
                <li><a class="text-muted" href="#">Government</a></li>
                <li><a class="text-muted" href="#">Gaming</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Team</a></li>
                <li><a class="text-muted" href="#">Locations</a></li>
                <li><a class="text-muted" href="#">Privacy</a></li>
                <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>
    </footer>
</main>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script crossorigin="anonymous"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>

</body>
</html>

rassilki/templates/rassilki/index.html
{% extends 'rassilki/base.html' %}

rassilki/templates/rassilki/mailing_confirm_delete.html
{% extends 'rassilki/home.html' %}
{% load static %}

{% block content %}
    <div class="col-12" align="center">
        <div class="rom ">
            <div class="col-6">
                <div class="card no-hover">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Are you sure you want to delete this Product: {{ object.title|title }}</p>
                            <button type="submit" class="btn btn-danger">Confirm Delete</button>
                            <a href="{% url 'rassilki:mailing-detail' object.pk  %}" class="btn btn-warning">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

rassilki/templates/rassilki/mailing_detail.html
{% extends 'rassilki/home.html' %}

{% block content %}
<style>
    .email-table {
        width: 100%;
        border-collapse: collapse;
    }

    .email-table th, .email-table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    .email-table th {
        background-color: #f2f2f2;
    }

    .email-table tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .email-table tr:hover {
        background-color: #ddd;
    }

    .subscribers-list {
        list-style-type: none;
        padding: 0;
    }

    .subscribers-list li {
        margin-bottom: 4px;
    }

    .button-container {
        margin-top: 10px;
        text-align: right;
    }

    .button-container a {
        text-decoration: none;
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border-radius: 5px;
        margin-right: 10px;
        display: inline-block;
    }

    .button-container a:hover {
        background-color: #0056b3;
    }
</style>

<table class="email-table">
    <thead>
    <tr>
        <th>Email Subject</th>
        <th>Message</th>
        <th>Time</th>
        <th>Status</th>
        <th>Subscribers</th>

    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ object.subject }}</td>
        <td>{{ object.body }}</td>
        <td>{{ object.send_time }}</td>
        {% if object.status == 1 %}
        <td>закончить</td>
        {% elif object.status == 2 %}
        <td>сохранить</td>
        {% elif object.status == 3 %}
        <td>запустить</td>
        {% endif %}
         <td>{{ object.get_status_display }}</td>
        <td>
            <ul class="subscribers-list">
                {% for client in object.client.all %}
                <li>{{ client.email }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
    </tbody>
</table>
<div class="button-container">
    <a href="{% url 'rassilki:mailing-delete' object.pk %}">Delete</a>
    <a href="{% url 'rassilki:mailing-update' object.pk %}">Edit</a>
    <a href="{% url 'rassilki:mailing-list' %}">Back to Campaign</a>
</div>
{% endblock %}

rassilki/templates/rassilki/mailing_list.html
{% extends 'rassilki/home.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <a class="btn btn-primary create-campaign-button" href="{% url 'rassilki:mailing-create' %}">Create
                Campaign</a>
        </div>
    </div>
    <div class="row mt-4">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-3 custom-card">
                <div class="card-body">
                    <h4 class="card-title">{{ object.mail_subject }}</h4>
                    <hr class="divider">
                    {% if object.period == 1%}
                    <p class="card-text"><strong>Periodicity:</strong> Daily</p>
                    {% elif object.period == 2%}
                    <p class="card-text"><strong>Periodicity:</strong> Weekly</p>
                    {% elif object.period == 3%}
                    <p class="card-text"><strong>Periodicity:</strong> Monthly</p>
                    {% endif %}
                    <p class="card-text"><strong>Send Time:</strong> {{ object.send_time }}</p>
                    <p class="card-text"><strong>Owner:</strong> {{ object.mail_owner }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-outline-primary btn-sm"
                               href="{% url 'rassilki:mailing-detail' object.pk %}">Details</a>
                        </div>
                        {% if object.mail_status == 1 %}
                        <small class="text-secondary">Finished</small>
                        {% elif object.mail_status == 2 %}
                        <small class="text-success">Created</small>
                        {% elif object.mail_status == 3 %}
                        <small class="text-danger">Running</small>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<style>
    .card-container {
        display: flex;
        justify-content: space-between; /* Adjust as needed */
    }

    .card {
        width: 100%;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s; /* Add transition for the hover effect */
    }

    /* Apply the hover effect */
    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }

    .card-title {
        font-size: 1.25rem;
        margin-bottom: 10px;
    }

    .card-text {
        font-size: 0.875rem;
        margin-bottom: 5px;
    }

    .btn-group {
        margin-top: 10px;
    }
</style>
{% endblock %}